export interface PoliticianInfo {
  name: string;
  party: string;
  term: string; // 선수
  note?: string; // 비고
}

export interface DistrictData {
  district: string;
  politician: PoliticianInfo;
}

export interface RegionData {
  name: string;
  count: number;
  districts: DistrictData[];
}

// 22대 국회의원 실제 데이터 (2025.12 기준)
export const ASSEMBLY_DATA: { [region: string]: RegionData } = {
  seoul: {
    name: "서울특별시",
    count: 48,
    districts: [
      { district: "종로구", politician: { name: "곽상언", party: "더불어민주당", term: "초선" } },
      { district: "중구·성동구 갑", politician: { name: "전현희", party: "더불어민주당", term: "3선" } },
      { district: "중구·성동구 을", politician: { name: "박성준", party: "더불어민주당", term: "재선" } },
      { district: "용산구", politician: { name: "권영세", party: "국민의힘", term: "5선" } },
      { district: "광진구 갑", politician: { name: "이정헌", party: "더불어민주당", term: "초선" } },
      { district: "광진구 을", politician: { name: "고민정", party: "더불어민주당", term: "재선" } },
      { district: "동대문구 갑", politician: { name: "안규백", party: "더불어민주당", term: "5선", note: "국방부장관 겸직" } },
      { district: "동대문구 을", politician: { name: "장경태", party: "더불어민주당", term: "재선" } },
      { district: "중랑구 갑", politician: { name: "서영교", party: "더불어민주당", term: "4선" } },
      { district: "중랑구 을", politician: { name: "박홍근", party: "더불어민주당", term: "4선" } },
      { district: "성북구 갑", politician: { name: "김영배", party: "더불어민주당", term: "재선" } },
      { district: "성북구 을", politician: { name: "김남근", party: "더불어민주당", term: "초선" } },
      { district: "강북구 갑", politician: { name: "천준호", party: "더불어민주당", term: "재선" } },
      { district: "강북구 을", politician: { name: "한민수", party: "더불어민주당", term: "초선" } },
      { district: "도봉구 갑", politician: { name: "김재섭", party: "국민의힘", term: "초선" } },
      { district: "도봉구 을", politician: { name: "오기형", party: "더불어민주당", term: "재선" } },
      { district: "노원구 갑", politician: { name: "우원식", party: "무소속", term: "5선", note: "국회의장" } },
      { district: "노원구 을", politician: { name: "김성환", party: "더불어민주당", term: "3선", note: "환경부장관 겸직" } },
      { district: "은평구 갑", politician: { name: "박주민", party: "더불어민주당", term: "3선", note: "보건복지위원장" } },
      { district: "은평구 을", politician: { name: "김우영", party: "더불어민주당", term: "초선" } },
      { district: "서대문구 갑", politician: { name: "김동아", party: "더불어민주당", term: "초선" } },
      { district: "서대문구 을", politician: { name: "김영호", party: "더불어민주당", term: "3선", note: "교육위원장" } },
      { district: "마포구 갑", politician: { name: "조정훈", party: "국민의힘", term: "재선" } },
      { district: "마포구 을", politician: { name: "정청래", party: "더불어민주당", term: "4선", note: "더불어민주당 대표" } },
      { district: "양천구 갑", politician: { name: "황희", party: "더불어민주당", term: "3선" } },
      { district: "양천구 을", politician: { name: "이용선", party: "더불어민주당", term: "재선" } },
      { district: "강서구 갑", politician: { name: "강선우", party: "더불어민주당", term: "재선" } },
      { district: "강서구 을", politician: { name: "진성준", party: "더불어민주당", term: "3선" } },
      { district: "강서구 병", politician: { name: "한정애", party: "더불어민주당", term: "4선", note: "기후위기특별위원장" } },
      { district: "구로구 갑", politician: { name: "이인영", party: "더불어민주당", term: "5선" } },
      { district: "구로구 을", politician: { name: "윤건영", party: "더불어민주당", term: "재선" } },
      { district: "금천구", politician: { name: "최기상", party: "더불어민주당", term: "재선" } },
      { district: "영등포구 갑", politician: { name: "채현일", party: "더불어민주당", term: "초선" } },
      { district: "영등포구 을", politician: { name: "김민석", party: "더불어민주당", term: "4선", note: "국무총리 겸직" } },
      { district: "동작구 갑", politician: { name: "김병기", party: "더불어민주당", term: "3선", note: "원내대표, 운영위원장" } },
      { district: "동작구 을", politician: { name: "나경원", party: "국민의힘", term: "5선" } },
      { district: "관악구 갑", politician: { name: "박민규", party: "더불어민주당", term: "초선" } },
      { district: "관악구 을", politician: { name: "정태호", party: "더불어민주당", term: "재선" } },
      { district: "서초구 갑", politician: { name: "조은희", party: "국민의힘", term: "재선" } },
      { district: "서초구 을", politician: { name: "신동욱", party: "국민의힘", term: "초선" } },
      { district: "강남구 갑", politician: { name: "서명옥", party: "국민의힘", term: "초선" } },
      { district: "강남구 을", politician: { name: "박수민", party: "국민의힘", term: "초선" } },
      { district: "강남구 병", politician: { name: "고동진", party: "국민의힘", term: "초선" } },
      { district: "송파구 갑", politician: { name: "박정훈", party: "국민의힘", term: "초선" } },
      { district: "송파구 을", politician: { name: "배현진", party: "국민의힘", term: "재선" } },
      { district: "송파구 병", politician: { name: "남인순", party: "더불어민주당", term: "4선" } },
      { district: "강동구 갑", politician: { name: "진선미", party: "더불어민주당", term: "4선" } },
      { district: "강동구 을", politician: { name: "이해식", party: "더불어민주당", term: "재선" } },
    ],
  },
  busan: {
    name: "부산광역시",
    count: 18,
    districts: [
      { district: "중구·영도구", politician: { name: "조승환", party: "국민의힘", term: "초선" } },
      { district: "서구·동구", politician: { name: "곽규택", party: "국민의힘", term: "초선" } },
      { district: "부산진구 갑", politician: { name: "정성국", party: "국민의힘", term: "초선" } },
      { district: "부산진구 을", politician: { name: "이헌승", party: "국민의힘", term: "4선" } },
      { district: "동래구", politician: { name: "서지영", party: "국민의힘", term: "초선" } },
      { district: "남구", politician: { name: "박수영", party: "국민의힘", term: "재선" } },
      { district: "북구 갑", politician: { name: "전재수", party: "더불어민주당", term: "3선", note: "해양수산부장관 겸직" } },
      { district: "북구 을", politician: { name: "박성훈", party: "국민의힘", term: "초선" } },
      { district: "해운대구 갑", politician: { name: "주진우", party: "국민의힘", term: "초선" } },
      { district: "해운대구 을", politician: { name: "김미애", party: "국민의힘", term: "재선" } },
      { district: "사하구 갑", politician: { name: "이성권", party: "국민의힘", term: "재선" } },
      { district: "사하구 을", politician: { name: "조경태", party: "국민의힘", term: "6선" } },
      { district: "금정구", politician: { name: "백종헌", party: "국민의힘", term: "재선" } },
      { district: "강서구", politician: { name: "김도읍", party: "국민의힘", term: "4선" } },
      { district: "연제구", politician: { name: "김희정", party: "국민의힘", term: "3선" } },
      { district: "수영구", politician: { name: "정연욱", party: "국민의힘", term: "초선" } },
      { district: "사상구", politician: { name: "김대식", party: "국민의힘", term: "초선" } },
      { district: "기장군", politician: { name: "정동만", party: "국민의힘", term: "재선" } },
    ],
  },
  daegu: {
    name: "대구광역시",
    count: 12,
    districts: [
      { district: "중구·남구", politician: { name: "김기웅", party: "국민의힘", term: "초선" } },
      { district: "동구·군위군 갑", politician: { name: "최은석", party: "국민의힘", term: "초선" } },
      { district: "동구·군위군 을", politician: { name: "강대식", party: "국민의힘", term: "재선" } },
      { district: "서구", politician: { name: "김상훈", party: "국민의힘", term: "4선" } },
      { district: "북구 갑", politician: { name: "우재준", party: "국민의힘", term: "초선" } },
      { district: "북구 을", politician: { name: "김승수", party: "국민의힘", term: "재선" } },
      { district: "수성구 갑", politician: { name: "주호영", party: "국민의힘", term: "6선", note: "국회부의장" } },
      { district: "수성구 을", politician: { name: "이인선", party: "국민의힘", term: "재선", note: "여성가족위원장" } },
      { district: "달서구 갑", politician: { name: "유영하", party: "국민의힘", term: "초선" } },
      { district: "달서구 을", politician: { name: "윤재옥", party: "국민의힘", term: "4선" } },
      { district: "달서구 병", politician: { name: "권영진", party: "국민의힘", term: "재선" } },
      { district: "달성군", politician: { name: "추경호", party: "국민의힘", term: "3선" } },
    ],
  },
  incheon: {
    name: "인천광역시",
    count: 13,
    districts: [
      { district: "중구·강화군·옹진군", politician: { name: "배준영", party: "국민의힘", term: "재선" } },
      { district: "동구·미추홀구 갑", politician: { name: "허종식", party: "더불어민주당", term: "재선" } },
      { district: "동구·미추홀구 을", politician: { name: "윤상현", party: "국민의힘", term: "5선" } },
      { district: "연수구 갑", politician: { name: "박찬대", party: "더불어민주당", term: "3선", note: "국회운영위원장" } },
      { district: "연수구 을", politician: { name: "정일영", party: "더불어민주당", term: "재선" } },
      { district: "남동구 갑", politician: { name: "맹성규", party: "더불어민주당", term: "3선", note: "국토교통위원장" } },
      { district: "남동구 을", politician: { name: "이훈기", party: "더불어민주당", term: "초선" } },
      { district: "부평구 갑", politician: { name: "노종면", party: "더불어민주당", term: "초선" } },
      { district: "부평구 을", politician: { name: "박선원", party: "더불어민주당", term: "초선" } },
      { district: "계양구 갑", politician: { name: "유동수", party: "더불어민주당", term: "3선" } },
      { district: "계양구 을", politician: { name: "궐원", party: "궐원", term: "-", note: "이재명 대통령 취임으로 의원직 사퇴" } },
      { district: "서구 갑", politician: { name: "김교흥", party: "더불어민주당", term: "3선", note: "문화체육관광위원장" } },
      { district: "서구 을", politician: { name: "이용우", party: "더불어민주당", term: "초선" } },
      { district: "서구 병", politician: { name: "모경종", party: "더불어민주당", term: "초선" } },
    ],
  },
  gwangju: {
    name: "광주광역시",
    count: 8,
    districts: [
      { district: "동구·남구 갑", politician: { name: "정진욱", party: "더불어민주당", term: "초선" } },
      { district: "동구·남구 을", politician: { name: "안도걸", party: "더불어민주당", term: "초선" } },
      { district: "서구 갑", politician: { name: "조인철", party: "더불어민주당", term: "초선" } },
      { district: "서구 을", politician: { name: "양부남", party: "더불어민주당", term: "초선" } },
      { district: "북구 갑", politician: { name: "정준호", party: "더불어민주당", term: "초선" } },
      { district: "북구 을", politician: { name: "전진숙", party: "더불어민주당", term: "초선" } },
      { district: "광산구 갑", politician: { name: "박균택", party: "더불어민주당", term: "초선" } },
      { district: "광산구 을", politician: { name: "민형배", party: "더불어민주당", term: "재선" } },
    ],
  },
  daejeon: {
    name: "대전광역시",
    count: 7,
    districts: [
      { district: "동구", politician: { name: "장철민", party: "더불어민주당", term: "재선" } },
      { district: "중구", politician: { name: "박용갑", party: "더불어민주당", term: "초선" } },
      { district: "서구 갑", politician: { name: "장종태", party: "더불어민주당", term: "초선" } },
      { district: "서구 을", politician: { name: "박범계", party: "더불어민주당", term: "4선" } },
      { district: "유성구 갑", politician: { name: "조승래", party: "더불어민주당", term: "3선" } },
      { district: "유성구 을", politician: { name: "황정아", party: "더불어민주당", term: "초선" } },
      { district: "대덕구", politician: { name: "박정현", party: "더불어민주당", term: "초선" } },
    ],
  },
  ulsan: {
    name: "울산광역시",
    count: 6,
    districts: [
      { district: "중구", politician: { name: "박성민", party: "국민의힘", term: "재선" } },
      { district: "남구 갑", politician: { name: "김상욱", party: "더불어민주당", term: "초선", note: "국민의힘 탈당 후 민주당 입당" } },
      { district: "남구 을", politician: { name: "김기현", party: "국민의힘", term: "5선" } },
      { district: "동구", politician: { name: "김태선", party: "더불어민주당", term: "초선" } },
      { district: "북구", politician: { name: "윤종오", party: "진보당", term: "재선", note: "진보당 원내대표" } },
      { district: "울주군", politician: { name: "서범수", party: "국민의힘", term: "재선" } },
    ],
  },
  sejong: {
    name: "세종특별자치시",
    count: 2,
    districts: [
      { district: "세종 갑", politician: { name: "김종민", party: "무소속", term: "3선" } },
      { district: "세종 을", politician: { name: "강준현", party: "더불어민주당", term: "재선" } },
    ],
  },
  gyeonggi: {
    name: "경기도",
    count: 59,
    districts: [
      { district: "수원시 갑", politician: { name: "김승원", party: "더불어민주당", term: "재선" } },
      { district: "수원시 을", politician: { name: "백혜련", party: "더불어민주당", term: "3선" } },
      { district: "수원시 병", politician: { name: "김영진", party: "더불어민주당", term: "3선" } },
      { district: "수원시 정", politician: { name: "김준혁", party: "더불어민주당", term: "초선" } },
      { district: "수원시 무", politician: { name: "염태영", party: "더불어민주당", term: "초선" } },
      { district: "성남시 수정구", politician: { name: "김태년", party: "더불어민주당", term: "5선" } },
      { district: "성남시 중원구", politician: { name: "이수진", party: "더불어민주당", term: "재선" } },
      { district: "성남시 분당구 갑", politician: { name: "안철수", party: "국민의힘", term: "4선" } },
      { district: "성남시 분당구 을", politician: { name: "김은혜", party: "국민의힘", term: "재선" } },
      { district: "의정부시 갑", politician: { name: "박지혜", party: "더불어민주당", term: "초선" } },
      { district: "의정부시 을", politician: { name: "이재강", party: "더불어민주당", term: "초선" } },
      { district: "안양시 만안구", politician: { name: "강득구", party: "더불어민주당", term: "재선" } },
      { district: "안양시 동안구 갑", politician: { name: "민병덕", party: "더불어민주당", term: "재선" } },
      { district: "안양시 동안구 을", politician: { name: "이재정", party: "더불어민주당", term: "3선" } },
      { district: "부천시 갑", politician: { name: "서영석", party: "더불어민주당", term: "재선" } },
      { district: "부천시 을", politician: { name: "김기표", party: "더불어민주당", term: "초선" } },
      { district: "부천시 병", politician: { name: "이건태", party: "더불어민주당", term: "초선" } },
      { district: "광명시 갑", politician: { name: "임오경", party: "더불어민주당", term: "재선" } },
      { district: "광명시 을", politician: { name: "김남희", party: "더불어민주당", term: "초선" } },
      { district: "평택시 갑", politician: { name: "홍기원", party: "더불어민주당", term: "재선" } },
      { district: "평택시 을", politician: { name: "이병진", party: "더불어민주당", term: "초선" } },
      { district: "평택시 병", politician: { name: "김현정", party: "더불어민주당", term: "초선" } },
      { district: "동두천시·양주시·연천군 갑", politician: { name: "정성호", party: "더불어민주당", term: "5선", note: "법무부장관 겸직" } },
      { district: "동두천시·양주시·연천군 을", politician: { name: "김성원", party: "국민의힘", term: "3선" } },
      { district: "안산시 갑", politician: { name: "양문석", party: "더불어민주당", term: "초선" } },
      { district: "안산시 을", politician: { name: "김현", party: "더불어민주당", term: "재선" } },
      { district: "안산시 병", politician: { name: "박해철", party: "더불어민주당", term: "초선" } },
      { district: "고양시 갑", politician: { name: "김성회", party: "더불어민주당", term: "초선" } },
      { district: "고양시 을", politician: { name: "한준호", party: "더불어민주당", term: "재선" } },
      { district: "고양시 병", politician: { name: "이기헌", party: "더불어민주당", term: "초선" } },
      { district: "고양시 정", politician: { name: "김영환", party: "더불어민주당", term: "초선" } },
      { district: "의왕시·과천시", politician: { name: "이소영", party: "더불어민주당", term: "재선" } },
      { district: "구리시", politician: { name: "윤호중", party: "더불어민주당", term: "5선", note: "행정안전부장관 겸직" } },
      { district: "남양주시 갑", politician: { name: "최민희", party: "더불어민주당", term: "재선", note: "과방위원장" } },
      { district: "남양주시 을", politician: { name: "김병주", party: "더불어민주당", term: "재선" } },
      { district: "남양주시 병", politician: { name: "김용민", party: "더불어민주당", term: "재선" } },
      { district: "오산시", politician: { name: "차지호", party: "더불어민주당", term: "초선" } },
      { district: "시흥시 갑", politician: { name: "문정복", party: "더불어민주당", term: "재선" } },
      { district: "시흥시 을", politician: { name: "조정식", party: "더불어민주당", term: "6선" } },
      { district: "군포시", politician: { name: "이학영", party: "더불어민주당", term: "4선", note: "국회부의장" } },
      { district: "하남시 갑", politician: { name: "추미애", party: "더불어민주당", term: "6선", note: "법제사법위원장" } },
      { district: "하남시 을", politician: { name: "김용만", party: "더불어민주당", term: "초선" } },
      { district: "용인시 갑", politician: { name: "이상식", party: "더불어민주당", term: "초선" } },
      { district: "용인시 을", politician: { name: "손명수", party: "더불어민주당", term: "초선" } },
      { district: "용인시 병", politician: { name: "부승찬", party: "더불어민주당", term: "초선" } },
      { district: "용인시 정", politician: { name: "이언주", party: "더불어민주당", term: "3선" } },
      { district: "파주시 갑", politician: { name: "윤후덕", party: "더불어민주당", term: "4선" } },
      { district: "파주시 을", politician: { name: "박정", party: "더불어민주당", term: "3선", note: "예산결산특별위원장" } },
      { district: "이천시", politician: { name: "송석준", party: "국민의힘", term: "3선" } },
      { district: "안성시", politician: { name: "윤종군", party: "더불어민주당", term: "초선" } },
      { district: "김포시 갑", politician: { name: "김주영", party: "더불어민주당", term: "재선" } },
      { district: "김포시 을", politician: { name: "박상혁", party: "더불어민주당", term: "재선" } },
      { district: "화성시 갑", politician: { name: "송옥주", party: "더불어민주당", term: "3선" } },
      { district: "화성시 을", politician: { name: "이준석", party: "개혁신당", term: "초선", note: "개혁신당 대표" } },
      { district: "화성시 병", politician: { name: "권칠승", party: "더불어민주당", term: "3선" } },
      { district: "화성시 정", politician: { name: "전용기", party: "더불어민주당", term: "재선" } },
      { district: "광주시 갑", politician: { name: "소병훈", party: "더불어민주당", term: "3선" } },
      { district: "광주시 을", politician: { name: "안태준", party: "더불어민주당", term: "초선" } },
      { district: "포천시·가평군", politician: { name: "김용태", party: "국민의힘", term: "초선" } },
      { district: "여주시·양평군", politician: { name: "김선교", party: "국민의힘", term: "재선" } },
    ],
  },
  gangwon: {
    name: "강원특별자치도",
    count: 8,
    districts: [
      { district: "춘천·철원·화천·양구 갑", politician: { name: "허영", party: "더불어민주당", term: "재선" } },
      { district: "춘천·철원·화천·양구 을", politician: { name: "한기호", party: "국민의힘", term: "4선" } },
      { district: "원주시 갑", politician: { name: "박정하", party: "국민의힘", term: "재선" } },
      { district: "원주시 을", politician: { name: "송기헌", party: "더불어민주당", term: "3선" } },
      { district: "강릉시", politician: { name: "권성동", party: "국민의힘", term: "5선" } },
      { district: "동해·태백·삼척·정선", politician: { name: "이철규", party: "국민의힘", term: "3선", note: "산업통상자원중소벤처기업위원장" } },
      { district: "속초·인제·고성·양양", politician: { name: "이양수", party: "국민의힘", term: "3선" } },
      { district: "홍천·횡성·영월·평창", politician: { name: "유상범", party: "국민의힘", term: "재선" } },
    ],
  },
  chungbuk: {
    name: "충청북도",
    count: 8,
    districts: [
      { district: "청주시 상당구", politician: { name: "이강일", party: "더불어민주당", term: "초선" } },
      { district: "청주시 서원구", politician: { name: "이광희", party: "더불어민주당", term: "초선" } },
      { district: "청주시 흥덕구", politician: { name: "이연희", party: "더불어민주당", term: "초선" } },
      { district: "청주시 청원구", politician: { name: "송재봉", party: "더불어민주당", term: "초선" } },
      { district: "충주시", politician: { name: "이종배", party: "국민의힘", term: "4선", note: "국무총리 인사청문특위위원장" } },
      { district: "제천시·단양군", politician: { name: "엄태영", party: "국민의힘", term: "재선" } },
      { district: "보은·옥천·영동·괴산", politician: { name: "박덕흠", party: "국민의힘", term: "4선" } },
      { district: "증평·진천·음성", politician: { name: "임호선", party: "더불어민주당", term: "재선" } },
    ],
  },
  chungnam: {
    name: "충청남도",
    count: 11,
    districts: [
      { district: "천안시 갑", politician: { name: "문진석", party: "더불어민주당", term: "재선" } },
      { district: "천안시 을", politician: { name: "이재관", party: "더불어민주당", term: "초선" } },
      { district: "천안시 병", politician: { name: "이정문", party: "더불어민주당", term: "재선" } },
      { district: "공주·부여·청양", politician: { name: "박수현", party: "더불어민주당", term: "재선" } },
      { district: "보령·서천", politician: { name: "장동혁", party: "국민의힘", term: "재선", note: "국민의힘 대표" } },
      { district: "아산시 갑", politician: { name: "복기왕", party: "더불어민주당", term: "재선" } },
      { district: "아산시 을", politician: { name: "궐원", party: "궐원", term: "-", note: "강훈식 대통령비서실장 임명" } },
      { district: "서산시·태안군", politician: { name: "성일종", party: "국민의힘", term: "3선", note: "국방위원장" } },
      { district: "논산·계룡·금산", politician: { name: "황명선", party: "더불어민주당", term: "초선" } },
      { district: "당진시", politician: { name: "어기구", party: "더불어민주당", term: "3선", note: "농림축산식품해양수산위원장" } },
      { district: "홍성·예산", politician: { name: "강승규", party: "국민의힘", term: "재선" } },
    ],
  },
  jeonbuk: {
    name: "전북특별자치도",
    count: 10,
    districts: [
      { district: "전주시 갑", politician: { name: "김윤덕", party: "더불어민주당", term: "3선", note: "국토교통부장관 겸직" } },
      { district: "전주시 을", politician: { name: "이성윤", party: "더불어민주당", term: "초선" } },
      { district: "전주시 병", politician: { name: "정동영", party: "더불어민주당", term: "5선", note: "통일부장관 겸직" } },
      { district: "군산·김제·부안 갑", politician: { name: "신영대", party: "더불어민주당", term: "재선" } },
      { district: "군산·김제·부안 을", politician: { name: "이원택", party: "더불어민주당", term: "재선" } },
      { district: "익산시 갑", politician: { name: "이춘석", party: "무소속", term: "4선", note: "더불어민주당 제명" } },
      { district: "익산시 을", politician: { name: "한병도", party: "더불어민주당", term: "3선", note: "예산결산특별위원장" } },
      { district: "정읍시·고창군", politician: { name: "윤준병", party: "더불어민주당", term: "재선" } },
      { district: "남원·장수·임실·순창", politician: { name: "박희승", party: "더불어민주당", term: "초선" } },
      { district: "완주·진안·무주", politician: { name: "안호영", party: "더불어민주당", term: "3선", note: "환경노동위원장" } },
    ],
  },
  jeonnam: {
    name: "전라남도",
    count: 10,
    districts: [
      { district: "목포시", politician: { name: "김원이", party: "더불어민주당", term: "재선" } },
      { district: "여수시 갑", politician: { name: "주철현", party: "더불어민주당", term: "재선" } },
      { district: "여수시 을", politician: { name: "조계원", party: "더불어민주당", term: "초선" } },
      { district: "순천·광양·곡성·구례 갑", politician: { name: "김문수", party: "더불어민주당", term: "초선" } },
      { district: "순천·광양·곡성·구례 을", politician: { name: "권향엽", party: "더불어민주당", term: "초선" } },
      { district: "나주시·화순군", politician: { name: "신정훈", party: "더불어민주당", term: "3선", note: "행정안전위원장" } },
      { district: "담양·함평·영광·장성", politician: { name: "이개호", party: "더불어민주당", term: "4선" } },
      { district: "고흥·보성·장흥·강진", politician: { name: "문금주", party: "더불어민주당", term: "초선" } },
      { district: "해남·완도·진도", politician: { name: "박지원", party: "더불어민주당", term: "5선" } },
      { district: "영암·무안·신안", politician: { name: "서삼석", party: "더불어민주당", term: "3선" } },
    ],
  },
  gyeongbuk: {
    name: "경상북도",
    count: 13,
    districts: [
      { district: "포항시 북구", politician: { name: "김정재", party: "국민의힘", term: "3선" } },
      { district: "포항시 남구·울릉군", politician: { name: "이상휘", party: "국민의힘", term: "초선" } },
      { district: "경주시", politician: { name: "김석기", party: "국민의힘", term: "3선", note: "외교통일위원장" } },
      { district: "김천시", politician: { name: "송언석", party: "국민의힘", term: "3선", note: "국민의힘 원내대표" } },
      { district: "안동시·예천군", politician: { name: "김형동", party: "국민의힘", term: "재선" } },
      { district: "구미시 갑", politician: { name: "구자근", party: "국민의힘", term: "재선" } },
      { district: "구미시 을", politician: { name: "강명구", party: "국민의힘", term: "초선" } },
      { district: "영주·영양·봉화", politician: { name: "임종득", party: "국민의힘", term: "초선" } },
      { district: "영천시·청도군", politician: { name: "이만희", party: "국민의힘", term: "3선" } },
      { district: "상주시·문경시", politician: { name: "임이자", party: "국민의힘", term: "3선", note: "기획재정위원장" } },
      { district: "경산시", politician: { name: "조지연", party: "국민의힘", term: "초선" } },
      { district: "의성·청송·영덕·울진", politician: { name: "박형수", party: "국민의힘", term: "재선" } },
      { district: "고령·성주·칠곡", politician: { name: "정희용", party: "국민의힘", term: "재선" } },
    ],
  },
  gyeongnam: {
    name: "경상남도",
    count: 16,
    districts: [
      { district: "창원시 의창구", politician: { name: "김종양", party: "국민의힘", term: "초선" } },
      { district: "창원시 성산구", politician: { name: "허성무", party: "더불어민주당", term: "초선" } },
      { district: "창원시 마산합포구", politician: { name: "최형두", party: "국민의힘", term: "재선" } },
      { district: "창원시 마산회원구", politician: { name: "윤한홍", party: "국민의힘", term: "3선", note: "정무위원장" } },
      { district: "창원시 진해구", politician: { name: "이종욱", party: "국민의힘", term: "초선" } },
      { district: "진주시 갑", politician: { name: "박대출", party: "국민의힘", term: "4선" } },
      { district: "진주시 을", politician: { name: "강민국", party: "국민의힘", term: "재선" } },
      { district: "통영시·고성군", politician: { name: "정점식", party: "국민의힘", term: "3선" } },
      { district: "사천·남해·하동", politician: { name: "서천호", party: "국민의힘", term: "초선" } },
      { district: "김해시 갑", politician: { name: "민홍철", party: "더불어민주당", term: "4선" } },
      { district: "김해시 을", politician: { name: "김정호", party: "더불어민주당", term: "3선", note: "산불피해지원대책특별위원장" } },
      { district: "밀양·의령·함안·창녕", politician: { name: "박상웅", party: "국민의힘", term: "초선" } },
      { district: "거제시", politician: { name: "서일준", party: "국민의힘", term: "재선" } },
      { district: "양산시 갑", politician: { name: "윤영석", party: "국민의힘", term: "4선", note: "연금개혁특별위원장" } },
      { district: "양산시 을", politician: { name: "김태호", party: "국민의힘", term: "4선" } },
      { district: "산청·함양·거창·합천", politician: { name: "신성범", party: "국민의힘", term: "3선", note: "정보위원장" } },
    ],
  },
  jeju: {
    name: "제주특별자치도",
    count: 3,
    districts: [
      { district: "제주시 갑", politician: { name: "문대림", party: "더불어민주당", term: "초선" } },
      { district: "제주시 을", politician: { name: "김한규", party: "더불어민주당", term: "재선" } },
      { district: "서귀포시", politician: { name: "위성곤", party: "더불어민주당", term: "3선" } },
    ],
  },
};

// 비례대표 의원 데이터
export interface ProportionalMember {
  rank: number;
  name: string;
  party: string;
  term: string;
  note?: string;
}

export const PROPORTIONAL_DATA: { [party: string]: ProportionalMember[] } = {
  "국민의미래": [
    { rank: 1, name: "최보윤", party: "국민의힘", term: "초선" },
    { rank: 2, name: "박충권", party: "국민의힘", term: "초선" },
    { rank: 3, name: "최수진", party: "국민의힘", term: "초선" },
    { rank: 4, name: "진종오", party: "국민의힘", term: "초선" },
    { rank: 5, name: "강선영", party: "국민의힘", term: "초선" },
    { rank: 6, name: "김건", party: "국민의힘", term: "초선" },
    { rank: 7, name: "김소희", party: "국민의힘", term: "초선" },
    { rank: 8, name: "인요한", party: "국민의힘", term: "초선", note: "의원직 사퇴" },
    { rank: 9, name: "김민전", party: "국민의힘", term: "초선" },
    { rank: 10, name: "김위상", party: "국민의힘", term: "초선" },
    { rank: 11, name: "한지아", party: "국민의힘", term: "초선" },
    { rank: 12, name: "유용원", party: "국민의힘", term: "초선" },
    { rank: 13, name: "조배숙", party: "국민의힘", term: "5선" },
    { rank: 14, name: "김장겸", party: "국민의힘", term: "초선" },
    { rank: 15, name: "김예지", party: "국민의힘", term: "재선" },
    { rank: 16, name: "안상훈", party: "국민의힘", term: "초선" },
    { rank: 17, name: "이달희", party: "국민의힘", term: "초선" },
    { rank: 18, name: "박준태", party: "국민의힘", term: "초선" },
    { rank: 19, name: "이소희", party: "국민의힘", term: "초선", note: "인요한 사퇴 후 승계" },
  ],
  "더불어민주연합": [
    { rank: 1, name: "서미화", party: "더불어민주당", term: "초선" },
    { rank: 2, name: "위성락", party: "더불어민주당", term: "초선", note: "국가안보실장 임명으로 사퇴" },
    { rank: 3, name: "백승아", party: "더불어민주당", term: "초선" },
    { rank: 4, name: "임광현", party: "무소속", term: "초선", note: "국세청장 임명으로 탈당" },
    { rank: 5, name: "정혜경", party: "진보당", term: "초선" },
    { rank: 6, name: "용혜인", party: "기본소득당", term: "재선" },
    { rank: 7, name: "오세희", party: "더불어민주당", term: "초선" },
    { rank: 8, name: "박홍배", party: "더불어민주당", term: "초선" },
    { rank: 9, name: "강유정", party: "더불어민주당", term: "초선", note: "대통령비서실 대변인 임명으로 사퇴" },
    { rank: 10, name: "한창민", party: "사회민주당", term: "초선", note: "사회민주당 원내대표" },
    { rank: 11, name: "전종덕", party: "진보당", term: "초선" },
    { rank: 12, name: "김윤", party: "더불어민주당", term: "초선" },
    { rank: 13, name: "임미애", party: "더불어민주당", term: "초선" },
    { rank: 14, name: "정을호", party: "더불어민주당", term: "초선" },
    { rank: 15, name: "손솔", party: "진보당", term: "초선", note: "위성락 사퇴 후 승계" },
    { rank: 16, name: "최혁진", party: "무소속", term: "초선", note: "강유정 사퇴 후 승계, 민주당 제명" },
    { rank: 17, name: "이주희", party: "더불어민주당", term: "초선", note: "임광현 의원직 상실 후 승계" },
  ],
  "조국혁신당": [
    { rank: 1, name: "박은정", party: "조국혁신당", term: "초선" },
    { rank: 2, name: "조국", party: "무소속", term: "초선", note: "피선거권 상실로 의원직 상실" },
    { rank: 3, name: "이해민", party: "조국혁신당", term: "초선" },
    { rank: 4, name: "신장식", party: "조국혁신당", term: "초선" },
    { rank: 5, name: "김선민", party: "조국혁신당", term: "초선" },
    { rank: 6, name: "김준형", party: "조국혁신당", term: "초선" },
    { rank: 7, name: "김재원", party: "조국혁신당", term: "초선" },
    { rank: 8, name: "황운하", party: "조국혁신당", term: "재선" },
    { rank: 9, name: "정춘생", party: "조국혁신당", term: "초선" },
    { rank: 10, name: "차규근", party: "조국혁신당", term: "초선" },
    { rank: 11, name: "강경숙", party: "조국혁신당", term: "초선" },
    { rank: 12, name: "서왕진", party: "조국혁신당", term: "초선", note: "조국혁신당 원내대표" },
    { rank: 13, name: "백선희", party: "조국혁신당", term: "초선", note: "조국 의원직 상실 후 승계" },
  ],
  "개혁신당": [
    { rank: 1, name: "이주영", party: "개혁신당", term: "초선" },
    { rank: 2, name: "천하람", party: "개혁신당", term: "초선", note: "개혁신당 원내대표" },
  ],
};

// 정당별 색상
export const PARTY_COLORS: { [party: string]: string } = {
  "더불어민주당": "#004EA2",
  "국민의힘": "#E61E2B",
  "조국혁신당": "#0073CF",
  "진보당": "#D6001C",
  "개혁신당": "#FF7920",
  "기본소득당": "#00C4B3",
  "사회민주당": "#E91E63",
  "무소속": "#808080",
};
